  
spring:
  application:
    name: git-config-server
 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajanraj18/configuration-server
          #username: xzrajanraj@gmail.com 
          #password: iamrajan@123
          default-label: main
          search-paths:
          - '*service*'
          - '*station*'


    
